M48
; DRILL file {KiCad 9.0.6} date 2025-12-07T22:25:54+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-07T22:25:54+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X43.2Y-62.2
X43.4Y-148.6
X152.4Y-43.16
X165.2Y-160.9
X180.69Y-115.36
M30
