M48
; DRILL file {KiCad 9.0.6} date 2025-12-07T22:16:42+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-07T22:16:42+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X41.5Y-109.5
X53.0Y-146.5
X70.0Y-37.0
X172.2Y-58.34
X178.06Y-143.44
M30
